### Random number generation in Python using Numpy

**Random numbers between 0 and 1:**

This type of data generation is useful in machine learning applications for initializing weights randomly in neural networks or for creating synthetic training datasets.

In [185]:
import numpy as np
random_number = np.random.rand()
print(random_number)

random_numbers = np.random.rand(5)
print(random_numbers)


0.5901774692235807
[0.14355602 0.27305608 0.9935317  0.50455294 0.90887833]


**Random numbers between 0 and 1:**

This type of data generation is useful in machine learning applications for initializing weights randomly in neural networks or for creating synthetic training datasets.

In [186]:
import numpy as np
random_number = np.random.rand()
print(random_number)

random_numbers = np.random.rand(5)
print(random_numbers)


0.36795839397543684
[0.01555628 0.69901499 0.44462373 0.57689624 0.50790487]


**Random integers within a specific range:**

Commonly used to simulate category data, such as user age or the number of visits to a website.

In [187]:
random_integer = np.random.randint(1, 100)
print(random_integer)
random_integers = np.random.randint(1, 100, size=10)
print(random_integers)


95
[46 34 82 46 66 69 66  1 47  5]


**Random numbers with normal (Gaussian) distribution:**

Useful in machine learning applications for generating features with normal distribution, such as the height of a population.

In [189]:
random_normal = np.random.randn()
print(random_normal)

random_normals = np.random.randn(10)
print(random_normals)


0.42443897353766213
[-1.30241915 -0.70921989 -0.21064275  0.57345427 -0.4120465  -1.9148519
  0.16553519 -0.24657842 -0.05760742  0.55546693]


**Random numbers with uniform distribution:**

Can be used to generate input data for machine learning models when there is suspected to be no dependency relationship.

In [191]:
random_uniform = np.random.uniform(0, 1)
print(random_uniform)

random_uniforms = np.random.uniform(0, 1, size=10)
print(random_uniforms)


0.8428462746151366
[0.34243968 0.50394423 0.84656002 0.53712222 0.27150258 0.6016902
 0.89884238 0.24188466 0.2055699  0.27004801]


**Random permutation of an array:**

Useful for cross-validation in machine learning models, where the dataset needs to be randomly divided into training and testing groups.

In [192]:
original_array = np.array([1, 2, 3, 4, 5])
np.random.shuffle(original_array)
print(original_array)


[3 2 5 4 1]


**Random choice of elements from an array:**

Can be used to create random training datasets or for random sampling in model evaluation.

In [193]:
options = ['a', 'b', 'c', 'd', 'e']
random_choice = np.random.choice(options)
print(random_choice)

choices = np.random.choice(options, size=3, replace=False)
print(choices)


b
['d' 'e' 'b']


**Shuffling data from multiple arrays simultaneously:**

Useful when maintaining correspondence between input data and output data in a dataset.

In [194]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array(['a', 'b', 'c', 'd', 'e'])
np.random.shuffle(array1)
np.random.shuffle(array2)
print(array1)
print(array2)


[4 1 2 5 3]
['a' 'd' 'e' 'c' 'b']


**Generating random numbers using a seed:**

Useful when reproducibility in random number generation is desired, which is crucial in scientific experiments and model validation.


In [195]:
np.random.seed(42)
random_number1 = np.random.rand()
np.random.seed(42)  # Reset the seed
random_number2 = np.random.rand()
print(random_number1, random_number2)


0.3745401188473625 0.3745401188473625


**Unique random integers:**

Useful when needing random indices for sampling from a dataset without replacement.

In [196]:
unique_numbers = np.random.choice(100, 10, replace=False)
print(unique_numbers)

[84 55 66 67 45 39 22 44 10  0]


**Generating random matrices:**

Used in various machine learning applications, such as initializing weight matrices in machine learning algorithms.

In [197]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.1988424  0.71134195 0.79017554]
 [0.60595997 0.92630088 0.65107703]
 [0.91495968 0.85003858 0.44945067]]
